version: 2

updates:
  # Dependencias NPM
  - package-ecosystem: "npm"
    directory: "/"              # donde está package.json
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "00:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "deps"

  # Imagen base del Dockerfile (nginx:alpine)
  - package-ecosystem: "docker"
    directory: "/"              # donde está el Dockerfile
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "docker"
      - "security"
    commit-message:
      prefix: "docker"

  # Actions (versiones de actions/checkout, build-push, etc.)
  - package-ecosystem: "github-actions"
    directory: "/"              # .github/workflows/
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "ci"
