version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: proyecto-final-devops-web:latest
    container_name: mi-web
    ports:
      - "8080:80"
    networks:
      - mi-red-interna
    depends_on:
      - api

  api:
    image: clue/json-server
    container_name: mi-api
    volumes:
      - ./db.json:/data/db.json:ro
    networks:
      - mi-red-interna

networks:
  mi-red-interna:
    driver: bridge